### ISSUE TITLE
Quote removal off-by-one (on ansible core 2.11.2)

### ISSUE THREAD

**Issue by grembo** [austinhyde/ansible-sshjail#34]
Changing this line

https://github.com/austinhyde/ansible-sshjail/blob/981674fdecd44d05d420f2a405a029b73846f205/sshjail.py#L357
to
```python
    cmd = sudoless[len(quotes):-len(quotes)] 
    if cmd.endswith("'"):
        cmd = cmd[:-1]
```

fixes the issue (even if it's just a workaround).

Example playbook that fails without the patch:

```yaml
---
- hosts: all
  gather_facts: False
  
  tasks:
   - name: install python
     raw: test -e /usr/local/bin/python || ( pkg install -y python )
```

**Comment by bikingcoder** [comment]
```
- hosts: customer@192.168.33.10
  name: Bootstrap Python
  gather_facts: no
  tasks:
    # last '_' is removed by bug in sshjail
    - name: Bootstrap Python
      raw: py_boot_
```
Have also had to work around this. `py_boot` is copied during jail creation. (excuse the hack!)
